### ISSUE TITLE
it seems version conflict

### ISSUE THREAD

**Issue by mngogo** [DiscipleD/staff-management-system#1]
it seems version conflict after KOA 3. it reports error when npm run dev, would you please update again? or guide me with your IM contact way. Thanks a lot！

**Comment by DiscipleD** [comment]
Did you mean about the follow log message?

> koa  deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md

That can be ignored. Otherwise, please provide more information.
